CRITICAL - 2023-12-07 12:26:25 --> Too few arguments to function App\Database\Migrations\AddDynamicColumnToOrg::__construct(), 0 passed in C:\xampp\htdocs\cc\system\Database\MigrationRunner.php on line 842 and exactly 1 expected
in APPPATH\Database\Migrations\2023-12-06-063626_AddNewColumnToOrg.php on line 13.
 1 SYSTEMPATH\Database\MigrationRunner.php(842): App\Database\Migrations\AddDynamicColumnToOrg->__construct()
 2 SYSTEMPATH\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
 3 APPPATH\Controllers\OrgCrud.php(65): CodeIgniter\Database\MigrationRunner->latest()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\OrgCrud->saveDynamicColumn()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrgCrud))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\cc\\public\\index.php')
ERROR - 2023-12-07 12:52:18 --> ErrorException: pg_query(): Query failed: ERROR:  syntax error at or near &quot;org&quot;
LINE 1: ALTER org ADD testasdhas varchar(255);
              ^ in C:\xampp\htdocs\cc\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 187)
#1 C:\xampp\htdocs\cc\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'ALTER org ADD t...')
#2 C:\xampp\htdocs\cc\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('ALTER org ADD t...')
#3 C:\xampp\htdocs\cc\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER org ADD t...')
#4 C:\xampp\htdocs\cc\system\Model.php(867): CodeIgniter\Database\BaseConnection->query('ALTER org ADD t...')
#5 C:\xampp\htdocs\cc\app\Controllers\OrgCrud.php(70): CodeIgniter\Model->__call('query', Array)
#6 C:\xampp\htdocs\cc\system\CodeIgniter.php(942): App\Controllers\OrgCrud->saveDynamicColumn()
#7 C:\xampp\htdocs\cc\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrgCrud))
#8 C:\xampp\htdocs\cc\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cc\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\cc\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
ERROR - 2023-12-07 12:56:26 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; of relation &quot;org&quot; already exists in C:\xampp\htdocs\cc\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 187)
#1 C:\xampp\htdocs\cc\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'ALTER TABLE org...')
#2 C:\xampp\htdocs\cc\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('ALTER TABLE org...')
#3 C:\xampp\htdocs\cc\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE org...')
#4 C:\xampp\htdocs\cc\system\Model.php(867): CodeIgniter\Database\BaseConnection->query('ALTER TABLE org...')
#5 C:\xampp\htdocs\cc\app\Controllers\OrgCrud.php(70): CodeIgniter\Model->__call('query', Array)
#6 C:\xampp\htdocs\cc\system\CodeIgniter.php(942): App\Controllers\OrgCrud->saveDynamicColumn()
#7 C:\xampp\htdocs\cc\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrgCrud))
#8 C:\xampp\htdocs\cc\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cc\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\cc\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-12-07 13:43:55 --> Undefined variable $user_obj
in APPPATH\Views\add-org.php on line 26.
 1 APPPATH\Views\add-org.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user_obj', 'C:\\xampp\\htdocs\\cc\\app\\Views\\add-org.php', 26)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\cc\\app\\Views\\add-org.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('add-org', [], true)
 5 APPPATH\Controllers\OrgCrud.php(21): view('add-org')
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\OrgCrud->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrgCrud))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\cc\\public\\index.php')
